### ISSUE TITLE
skills?

### ISSUE THREAD

**Issue by adamf663** [stanford-oval/almond-server#112]
When I run almond-server and connect to its port 3000 web server, there are only the smallest list of available skills.  I specifically want it to connect to my home assistant installation, but its skill isn't available and there is no option on any of the port 3000 web pages to add it.
Is there any useful documentation for running almond-server other than the single mention of the 'podman run ...' command?  That mention doesn't even document the docker image's parameters

**Comment by gcampax** [comment]
Hi @adamf663 , thanks for your report. I am assuming you're testing Almond 1.99 or the master branch?
Those are development versions, so to speak. They use a newer version of the natural language engine, which does not yet support most of the skills, including Home Assistant. We're working to add back support for Home Assistant, but in the meantime I suggest using version 1.8.
You can find a slightly longer explanation at https://wiki.almond.stanford.edu/release-planning/one-point-ninetynine
or in the release announcement at https://community.almond.stanford.edu/t/new-release-almond-1-99/326

As for options, there are no command line options supported by almond-server. There are some configuration options available in config.js or through environment variables. These are mainly for non-standard configurations and/or integrating Almond in other software with complex proxy setups. Users are not expected to change them.

**Comment by adamf663** [comment]
I'm still in the process of understand almond.
1) When I inspected the podman image, the version was 19.03.8.  I then exec'd into the running container and see that /opt/almond/HISTORY has version 1.99.0 at the top.
2) I noticed a link on the almond 'get almond' page titled 'smart speaker' with a link to this project.
The hassio home assistant build has an almond addon that offers more plugins, but I have no interest in running almond on a puny pi.  I want it running on my home server, a octacore ryzen with tons of SSD (and a 40T mechanical disk RAID6)  
The almond-cloud project is looking like the way to go.  (first, I'll try almond-server version 1.8)

**Comment by gcampax** [comment]
Hey sorry for the delayed reply.

- Not sure what 19.03.8 is, it looks like the version of docker? I can't think of anything with that version... Almond is either 1.99.* or 1.8.*

- The Almond assistant is composed by multiple parts that are running in different servers. What you're looking to run is the Almond engine, which is the client that hosts your credentials and connects to various services. For a single user, almond-server is enough. almond-cloud is a multi-user installation, which you probably don't need. You don't need a big spec machine.
The "real work" you're referring to is probably either speech-to-text (always in the cloud), or semantic parsing (natural language to ThingTalk code). The latter is normally executed on a server at Stanford, so that also doesn't need a big server on your own.
You can choose to host your own semantic parsing server using almond-cloud or using genie-toolkit - the latter is a bit easier to set up.

**Comment by nrser** [comment]
Hope we have answered your questions, feel free to engage further on our [forum](https://community.almond.stanford.edu)

**Comment by adamf663** [comment]
Thanks for the clarifications.  Although cloud processing is easier, I truly want to (eventually) not rely on the cloud for any of my home automation.  I'll first use the cloud and in the meantime figure out how to set up the engine locally.
