### ISSUE TITLE
Instructions for running on Docker

### ISSUE THREAD

**Issue by carlos-sarmiento** [stanford-oval/almond-server#35]
The instructions on the README seem to imply that running almond-server on Docker is more difficult than on Podman (the sentence `and thus access PulseAudio from your normal session`). I don't understand what is needed to access PulseAudio from docker (I've used docker extensively, but never with anything related to sound) and so this makes me thing instructions for running on Docker would be different.

I understand the reason why the README recommends Podman vs. Docker, but since I use Docker extensively, installing Podman just to run almond-server seems overkill. 

Would it be possible to provide an equivalent Docker Run command?

**Comment by gcampax** [comment]
podman and docker use the same command line (podman is meant as a drop-in replacement for docker). The problem is permissions: if you use podman, and pass `--userns=keep-id`, the container is run with the same host UID as the running user, which means you can access the PulseAudio socket without problems. If you use docker, the container is run by the docker daemon, which runs as the user `root` or `docker`, so the user inside the container won't have the right permissions to access the PulseAudio socket on the host.
If you're setting up a small embedded device, you might be able to fiddle with permissions enough that you can run in docker (for example using PulseAudio system-mode instead of user-mode), but that's not recommended for usage in a normal desktop/laptop.
